CREATE TABLE employees (
    id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    company_id UUID NOT NULL,
    office_id UUID,
    employee_code VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    fiscal_code VARCHAR(50),
    email VARCHAR(150),
    residence_country VARCHAR(100),
    residence_region VARCHAR(100),
    residence_area VARCHAR(100),
    residence_global_zip_code VARCHAR(20),
    residence_city VARCHAR(120),
    residence_address_line1 VARCHAR(150),
    residence_street_number VARCHAR(30),
    residence_address_line2 VARCHAR(150),
    residence_postal_code VARCHAR(20),
    national_identifier VARCHAR(100),
    national_identifier_type VARCHAR(50),
    birth_date DATE,
    birth_country VARCHAR(100),
    birth_region VARCHAR(100),
    birth_area VARCHAR(100),
    birth_city VARCHAR(120),
    gender VARCHAR(50),
    marital_status VARCHAR(50),
    international_phone_prefix VARCHAR(10),
    phone_number VARCHAR(50),
    emergency_contact_name VARCHAR(150),
    emergency_contact_phone_prefix VARCHAR(10),
    emergency_contact_phone_number VARCHAR(50),
    has_children BOOLEAN NOT NULL DEFAULT FALSE,
    children_count INTEGER NOT NULL DEFAULT 0,
    department VARCHAR(50),
    job_title VARCHAR(50),
    contract_type VARCHAR(50),
    employment_status VARCHAR(50) NOT NULL,
    work_mode VARCHAR(50),
    hire_date DATE,
    termination_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    gdpr_consent_at TIMESTAMP WITH TIME ZONE,
    privacy_policy_accepted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT uk_employees_tenant_employee_code UNIQUE (tenant_id, employee_code),
    CONSTRAINT fk_employees_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_employees_company FOREIGN KEY (company_id) REFERENCES company_profiles (id),
    CONSTRAINT fk_employees_office FOREIGN KEY (office_id) REFERENCES office_locations (id),
    CONSTRAINT ck_employees_children_count CHECK (children_count >= 0)
);

CREATE INDEX idx_employees_tenant_id ON employees (tenant_id);
CREATE INDEX idx_employees_company_id ON employees (company_id);
CREATE INDEX idx_employees_office_id ON employees (office_id);
CREATE INDEX idx_employees_employment_status ON employees (employment_status);
