spring:
  application:
    name: hrm-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/hrm_db
    username: hrm_user
    password: hrm_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always