spring:
  datasource:
    url: ${HRM_DB_URL}
    username: ${HRM_DB_USERNAME}
    password: ${HRM_DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

management:
  endpoint:
    health:
      show-details: never

hrm:
  security:
    jwt:
      secret: ${HRM_JWT_SECRET}
      expires-in: ${HRM_JWT_EXPIRES_IN:3600}
